= pytogo release notes =
// SPDX-FileCopyrightText: (C) Eric S. Raymond <esr@thyrsus.com>
// SPDX-License-Identifier: CC-BY-4.0

1.12: 2024-03-22::
   Translate ''' literals.
   Translate Python 3 sys.maxsize.
   Documentation improvements

1.11: 2024-02-09::
   Documentation fix: correct command-line synopsis.
   Translate pwd.getpwuid and getpwnam calls.

1.10: 2024-01-09::
   Massage Python-style variable and function names with _ to camelCase.

1.9: 2023-10-24::
   Strip out __slots__ declarations.
   Type-decorate "self" in class methods properly.
   Improved handling of comment after comditional guard.

1.8: 2023-04-20::
   Translate if and while statements with inline bodies.

1.7: 2022-01-22::
   Translate a few more entry points in Python os and sys.

1.6: 2020-05-02::
   Translate additional library calls.

1.5: 2020-02-04::
   Add class as a block starter keyword.
   More math library functions are translated.
   Simple integer/string/float constant declarations are translated.

1.4: 2018-10-23::
   Fix for error in translation of os.sep.
   Translate os.path.realpath

1.3: 2018-10-22::
   Some cases where string.Contains() should be applied get it.
   "+= 1" and "-=1" become ++ and --.
   Prevent false positives in assignment code.
   Manual page now includes a guide to preparing for translation.
   More system variables and functions translated: os.sep, os.path.isabs.
   import from future lines are discarded.

1.2: 2018-10-07::
   PEP484 type hints are now converted into Go type signatures.
   Without PEP484 hints, return types of functions are now sometimes deduced.
   Docstrings are moved to the godoc-preferred position above the signature.
   Python math and cmath library functions are mapped over.
   Python shebang lines are recognized and converted to "package main".
   Map variadic function sgnatures to use "..."
   Import translation.

1.1: 2018-10-01::
   for-loop idioms for walking a list or dictionary are translated.
   Fixed bugs in processing of multiline strings and midline colon.

1.0: 2018-09-30::
   Initial release.
